# Generated by Django 3.2.24 on 2024-08-19 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0009_membership_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20240520_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='membership',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='memberships.membership'),
        ),
        migrations.CreateModel(
            name='Maillist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
