# Generated by Django 3.2.24 on 2024-08-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20240819_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='membership',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.EmailField(max_length=254),
        ),
    ]
