# Generated by Django 3.2.24 on 2024-08-28 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '0009_membership_image'),
        ('profiles', '0004_auto_20240828_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='membership',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='memberships.membership'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
