# Generated by Django 3.2.24 on 2024-03-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='cost',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='membership',
            name='image',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to=None),
        ),
    ]
