# Generated by Django 3.2.24 on 2024-04-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20240329_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
