# Generated by Django 3.2.24 on 2024-04-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membership_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
