# Generated by Django 3.2.24 on 2024-04-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_auto_20240414_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stripe_price',
            field=models.IntegerField(default=1),
        ),
    ]
