# Generated by Django 3.2.24 on 2024-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0008_remove_membership_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
